# -*- coding: utf-8 -*-
"""basic vacuum cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kv8b8xIziJD1NlnwdNKPMoO-839Po5Bf
"""

agent_table = {
    ('Dirty', 'A'): 'Suck',
    ('Dirty', 'B'): 'Suck',
    ('Clean', 'A'): 'MoveRight',
    ('Clean', 'B'): 'MoveLeft'
}

class VacuumCleaner:
    def __init__(self, location='A'):
        self.location = location
        self.dirt = {'A': 50, 'B': 50}

    def percept(self):
        if self.dirt[self.location] > 0:
            return 'Dirty'
        else:
            return 'Clean'

    def act(self, action):
        if action == 'Suck':
            print(f"Cleaning location {self.location}...")
            self.dirt[self.location] = 0
            print("Cleaned = 50%")

        elif action == 'MoveRight':
            print("Moving RIGHT to location B")
            self.location = 'B'

        elif action == 'MoveLeft':
            print("Moving LEFT to location A")
            self.location = 'A'

        else:
            print("No Move - Vacuum is idle")

def table_driven_agent(percept, location):
    return agent_table.get((percept, location), 'NoMove')


if __name__ == "__main__":
    vacuum = VacuumCleaner()

    print("Output:\n")
    print("Initial Dirt Status:")
    print("Location A: 50%")
    print("Location B: 50%\n")

    for _ in range(4):
        percept = vacuum.percept()
        action = table_driven_agent(percept, vacuum.location)

        print("Current location:", vacuum.location)
        print("Percept:", percept)
        print("Action:", action)

        vacuum.act(action)

        print("Dirt Status:")
        print("A:", vacuum.dirt['A'], "%  B:", vacuum.dirt['B'], "%\n")

    print("Performance Summary:")
    print("Cleaned = 50%")
    print("Not cleaned = 0%")
    print("Dirt Remaining = 0%")